const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Flash,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Text.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SetMaxFallSpeed,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Behaviors.Platform.Acts.SetDoubleJumpEnabled,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.Platform.Acts.SetAcceleration,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Acts.SetDeceleration,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsOverlapping
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{Solid: 0},
	{Tilemap: 0},
	{Flash: 0},
	{PlayerAnim: 0},
	{flight: 0},
	{hover: 0},
	{doubleJump: 0},
	{dash: 0},
	{dashDuration: 0},
	{dashing: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{PlayerBox: 0},
	{Keyboard: 0},
	{Sine: 0},
	{Wings: 0},
	{Darkness: 0},
	{Hover: 0},
	{DoubleJump: 0},
	{Dash: 0},
	{Particles: 0},
	{fulfilled: 0},
	{ConstructionWorker: 0},
	{Sun: 0},
	{lock: 0},
	{lock2: 0},
	{Moon: 0},
	{TiledBackgroundRed: 0},
	{Spike: 0},
	{Spoke: 0},
	{CurrentCheckpoint: 0},
	{Checkpoint1: 0},
	{Checkpoint2: 0},
	{NightSky: 0},
	{DaySky: 0},
	{Checkpoint3: 0},
	{lock3: 0},
	{UpgradeRemover: 0},
	{Text: 0},
	{Checkpoint4: 0},
	{ConstructOMobile: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	PlayerAnim: class extends self.ISpriteInstance {},
	PlayerBox: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Wings: class extends self.ISpriteInstance {},
	Darkness: class extends self.ISpriteInstance {},
	Hover: class extends self.ISpriteInstance {},
	DoubleJump: class extends self.ISpriteInstance {},
	Dash: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	ConstructionWorker: class extends self.ISpriteInstance {},
	Sun: class extends self.ISpriteInstance {},
	lock: class extends self.ISpriteInstance {},
	lock2: class extends self.ISpriteInstance {},
	Moon: class extends self.ISpriteInstance {},
	TiledBackgroundRed: class extends self.ITiledBackgroundInstance {},
	Spike: class extends self.ISpriteInstance {},
	Spoke: class extends self.ISpriteInstance {},
	CurrentCheckpoint: class extends self.ISpriteInstance {},
	Checkpoint1: class extends self.ISpriteInstance {},
	Checkpoint2: class extends self.ISpriteInstance {},
	NightSky: class extends self.ITiledBackgroundInstance {},
	DaySky: class extends self.ITiledBackgroundInstance {},
	Checkpoint3: class extends self.ISpriteInstance {},
	lock3: class extends self.ISpriteInstance {},
	UpgradeRemover: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Checkpoint4: class extends self.ISpriteInstance {},
	ConstructOMobile: class extends self.ISpriteInstance {}
}