const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Plugins.Particles,
		C3.Behaviors.Flash,
		C3.Plugins.Tilemap,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.gamepad,
		C3.Plugins.Button,
		C3.Plugins.Browser,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.gamepad.Cnds.CompareAxis,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SetMaxFallSpeed,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.gamepad.Cnds.OnButtonUp,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.TiledBg.Acts.SetZElevation,
		C3.Plugins.Tilemap.Acts.MoveToTop,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Text.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Behaviors.Platform.Acts.SetDoubleJumpEnabled,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Platform.Acts.SetAcceleration,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Acts.SetDeceleration,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Behaviors.Platform.Acts.FallThrough,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Browser.Acts.Close
	];
};
self.C3_JsPropNameTable = [
	{Checkpoint1: 0},
	{Checkpoint2: 0},
	{Checkpoint3: 0},
	{Checkpoint4: 0},
	{fulfilled: 0},
	{Solid: 0},
	{ConstructionWorker: 0},
	{ConstructOMobile: 0},
	{CurrentCheckpoint: 0},
	{Darkness: 0},
	{dash: 0},
	{Sine: 0},
	{Dash: 0},
	{DaySky: 0},
	{DoubleJump: 0},
	{Hover: 0},
	{lock: 0},
	{lock2: 0},
	{lock3: 0},
	{Moon: 0},
	{NightSky: 0},
	{Particles: 0},
	{Flash: 0},
	{PlayerAnim: 0},
	{Spike: 0},
	{Spoke: 0},
	{Sun: 0},
	{TiledBackground: 0},
	{TiledBackgroundRed: 0},
	{Tilemap: 0},
	{UpgradeRemover: 0},
	{Wings: 0},
	{lock4: 0},
	{Checkpoint5: 0},
	{flight: 0},
	{hover: 0},
	{doubleJump: 0},
	{dashDuration: 0},
	{dashing: 0},
	{dashCooldown: 0},
	{bunny: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{PlayerBox: 0},
	{Keyboard: 0},
	{PopUpText: 0},
	{Gamepad: 0},
	{PlayButton: 0},
	{ExitButton: 0},
	{Browser: 0},
	{TimerText: 0},
	{Array: 0},
	{BestTimeText: 0},
	{MainMenuBackground: 0},
	{DebugText: 0},
	{BunnyGirl: 0},
	{Bunny: 0},
	{HighScoreText: 0},
	{LASTTIME: 0},
	{LastTimeText: 0},
	{Audio: 0},
	{CreditText: 0},
	{CreditsBackButton: 0},
	{CreditsButton: 0},
	{Bunny2: 0},
	{BlueX: 0},
	{GreenY: 0},
	{RedA: 0},
	{Letter: 0},
	{AnalogPercent: 0},
	{TimerRunning: 0},
	{GameTime: 0},
	{BestTime: 0},
	{Running: 0},
	{Debug: 0},
	{LastTime: 0}
];

self.InstanceType = {
	Checkpoint1: class extends self.ISpriteInstance {},
	Checkpoint2: class extends self.ISpriteInstance {},
	Checkpoint3: class extends self.ISpriteInstance {},
	Checkpoint4: class extends self.ISpriteInstance {},
	ConstructionWorker: class extends self.ISpriteInstance {},
	ConstructOMobile: class extends self.ISpriteInstance {},
	CurrentCheckpoint: class extends self.ISpriteInstance {},
	Darkness: class extends self.ISpriteInstance {},
	Dash: class extends self.ISpriteInstance {},
	DaySky: class extends self.ITiledBackgroundInstance {},
	DoubleJump: class extends self.ISpriteInstance {},
	Hover: class extends self.ISpriteInstance {},
	lock: class extends self.ISpriteInstance {},
	lock2: class extends self.ISpriteInstance {},
	lock3: class extends self.ISpriteInstance {},
	Moon: class extends self.ISpriteInstance {},
	NightSky: class extends self.ITiledBackgroundInstance {},
	Particles: class extends self.IParticlesInstance {},
	PlayerAnim: class extends self.ISpriteInstance {},
	Spike: class extends self.ISpriteInstance {},
	Spoke: class extends self.ISpriteInstance {},
	Sun: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackgroundRed: class extends self.ITiledBackgroundInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	UpgradeRemover: class extends self.ISpriteInstance {},
	Wings: class extends self.ISpriteInstance {},
	lock4: class extends self.ISpriteInstance {},
	Checkpoint5: class extends self.ISpriteInstance {},
	PlayerBox: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	PopUpText: class extends self.ITextInstance {},
	Gamepad: class extends self.IInstance {},
	PlayButton: class extends self.IButtonInstance {},
	ExitButton: class extends self.IButtonInstance {},
	Browser: class extends self.IInstance {},
	TimerText: class extends self.ITextInstance {},
	Array: class extends self.IArrayInstance {},
	BestTimeText: class extends self.ITextInstance {},
	MainMenuBackground: class extends self.ISpriteInstance {},
	DebugText: class extends self.ITextInstance {},
	BunnyGirl: class extends self.ISpriteInstance {},
	Bunny: class extends self.ISpriteInstance {},
	HighScoreText: class extends self.ITextInstance {},
	LASTTIME: class extends self.ITextInstance {},
	LastTimeText: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	CreditText: class extends self.ITextInstance {},
	CreditsBackButton: class extends self.IButtonInstance {},
	CreditsButton: class extends self.IButtonInstance {},
	Bunny2: class extends self.ISpriteInstance {},
	BlueX: class extends self.ISpriteInstance {},
	GreenY: class extends self.ISpriteInstance {},
	RedA: class extends self.ISpriteInstance {},
	Letter: class extends self.ISpriteInstance {}
}